name: Check Golang

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Golang
        uses: actions/checkout@v4
        uses: actions/setup-go@v5
          with:
            go-version: stable
            
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60