name: Check Golang

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Show files
        run: ls -rl 

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Check task 15
        run: golangci-lint run lib/task15/golang.go

      - name: Check task 16
        run: golangci-lint run lib/task16/golang.go
        
